-- Client testimonials shown on the homepage and /about. Rows are only ever
-- created by an admin: nothing here is generated by the site.

create table public.testimonials (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text,
  company text,
  avatar_path text,
  avatar_alt text,
  testimonial text not null,
  rating smallint not null default 5,
  featured boolean not null default false,
  sort_order integer not null default 0,
  status public.content_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint testimonials_name_length check (char_length(name) between 2 and 60),
  constraint testimonials_role_length check (role is null or char_length(role) between 2 and 60),
  constraint testimonials_company_length check (company is null or char_length(company) between 2 and 60),
  constraint testimonials_body_length check (char_length(testimonial) between 20 and 800),
  constraint testimonials_rating_range check (rating between 1 and 5),
  constraint testimonials_avatar_alt_required check (
    avatar_path is null or char_length(btrim(coalesce(avatar_alt, ''))) > 0
  ),
  constraint testimonials_avatar_alt_length check (avatar_alt is null or char_length(avatar_alt) <= 120)
);

create index testimonials_status_sort_idx on public.testimonials (status, sort_order);
create index testimonials_featured_idx on public.testimonials (status, featured, sort_order);

create trigger testimonials_set_updated_at
  before update on public.testimonials
  for each row execute function public.set_updated_at();

alter table public.testimonials enable row level security;

create policy "Published testimonials are public"
  on public.testimonials for select
  to anon, authenticated
  using (status = 'published');

create policy "Admins can read all testimonials"
  on public.testimonials for select
  to authenticated
  using ((select public.is_admin()));

create policy "Admins can create testimonials"
  on public.testimonials for insert
  to authenticated
  with check ((select public.is_admin()));

create policy "Admins can update testimonials"
  on public.testimonials for update
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

create policy "Admins can delete testimonials"
  on public.testimonials for delete
  to authenticated
  using ((select public.is_admin()));
